name: .NET Core

on:
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.x
    - name: Build OperatorSharp with dotnet
      run: dotnet build --configuration Release src/OperatorSharp.sln --version-suffix prerelease-$(date +%Y%m%d%H%M%S)
    - name: Package OperatorSharp
      run: dotnet pack --configuration Release src/OperatorSharp.sln --version-suffix prerelease-$(date +%Y%m%d%H%M%S) -o ../artifacts/
    - name: Publish All
      run: |
           for f in ../artifacts/*.nupkg
           do
             dotnet nuget push $f -k ${NUGET_TOKEN} -s https://api.nuget.org/v3/index.json
           done
      shell: bash
      env:
        NUGET_TOKEN: ${{ secrets.NuGetKey }}
